version: "3.7"

services:

    nytlabels-fetch-annotation:
        image: dockermediacloud/nytlabels-fetch-annotation:latest
        init: true
        stop_signal: SIGKILL
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/nytlabels-fetch-annotation/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../nytlabels-base/src/
              target: /opt/mediacloud/src/nytlabels-base/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - postgresql-pgbouncer

    postgresql-pgbouncer:
        image: dockermediacloud/postgresql-pgbouncer:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 6432
        volumes:
            - type: bind
              source: ./../postgresql-pgbouncer/conf/
              target: /etc/pgbouncer/
        depends_on:
            - postgresql-server

    postgresql-server:
        image: dockermediacloud/postgresql-server:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 5432
        volumes:
            - type: bind
              source: ./../postgresql-server/bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../postgresql-server/schema/
              target: /opt/mediacloud/schema/
            - type: bind
              source: ./../postgresql-server/conf/
              target: /etc/postgresql/12/main/
