version: "3.7"

services:

    topics-base:
        image: dockermediacloud/topics-base:latest
        init: true
        stop_signal: SIGKILL
        environment:
            # Tests call mock API endpoint and don't need API credentials
            MC_TWITTER_ACCESS_TOKEN: "mock access token"
            MC_TWITTER_ACCESS_TOKEN_SECRET: "mock access token secret"
            MC_TWITTER_CONSUMER_KEY: "mock consumer key"
            MC_TWITTER_CONSUMER_SECRET: "mock consumer secret"
        volumes:
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/topics-base/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
            - type: bind
              source: ./../extract-and-vector/src/
              target: /opt/mediacloud/src/extract-and-vector/
        depends_on:
            - postgresql-pgbouncer
            - rabbitmq-server
            # For test_generate_story:
            - extract-and-vector

    extract-and-vector:
        image: dockermediacloud/extract-and-vector:latest
        init: true
        stop_signal: SIGKILL
        volumes:
            - type: bind
              source: ./../extract-and-vector/bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../extract-and-vector/src/
              target: /opt/mediacloud/src/extract-and-vector/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - postgresql-pgbouncer
            - extract-article-from-page

    extract-article-from-page:
        image: dockermediacloud/extract-article-from-page:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 8080
        volumes:
            - type: bind
              source: ./../extract-article-from-page/bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../extract-article-from-page/src/
              target: /opt/mediacloud/src/extract-article-from-page/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/

    postgresql-pgbouncer:
        image: dockermediacloud/postgresql-pgbouncer:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 6432
        volumes:
            - type: bind
              source: ./../postgresql-pgbouncer/conf/
              target: /etc/pgbouncer/
        depends_on:
            - postgresql-server

    postgresql-server:
        image: dockermediacloud/postgresql-server:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 5432
        volumes:
            - type: bind
              source: ./../postgresql-server/bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../postgresql-server/schema/
              target: /opt/mediacloud/schema/
            - type: bind
              source: ./../postgresql-server/conf/
              target: /etc/postgresql/12/main/

    rabbitmq-server:
        image: dockermediacloud/rabbitmq-server:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 5672
            - 15672
        volumes:
            - type: bind
              source: ./../rabbitmq-server/conf/
              target: /etc/rabbitmq/
