version: "3.7"

services:

    postgresql-pgadmin:
        image: dockermediacloud/postgresql-pgadmin:latest
        init: true
        stop_signal: SIGKILL
        ports:
            # Expose to host for debugging
            - "5050:5050"
        volumes:
            - type: bind
              source: ./pgadmin.sh
              target: /pgadmin.sh
            - type: bind
              source: ./mediacloud.pgpass
              target: /var/lib/pgadmin/storage/mediacloud_mediacloud.org/mediacloud.pgpass
        depends_on:
            - postgresql-pgbouncer

    postgresql-pgbouncer:
        image: dockermediacloud/postgresql-pgbouncer:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 6432
        volumes:
            - type: bind
              source: ./../postgresql-pgbouncer/conf/
              target: /etc/pgbouncer/
        depends_on:
            - postgresql-server

    postgresql-server:
        image: dockermediacloud/postgresql-server:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 5432
        volumes:
            - type: bind
              source: ./../postgresql-server/bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../postgresql-server/schema/
              target: /opt/mediacloud/schema/
            - type: bind
              source: ./../postgresql-server/conf/
              target: /etc/postgresql/12/main/
