version: "3.7"

services:

    rescrape-media:
        image: dockermediacloud/rescrape-media:latest
        init: true
        stop_signal: SIGKILL
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/rescrape-media/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - postgresql-pgbouncer
            - rabbitmq-server

    postgresql-pgbouncer:
        image: dockermediacloud/postgresql-pgbouncer:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 6432
        volumes:
            - type: bind
              source: ./../postgresql-pgbouncer/conf/
              target: /etc/pgbouncer/
        depends_on:
            - postgresql-server

    postgresql-server:
        image: dockermediacloud/postgresql-server:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 5432
        volumes:
            - type: bind
              source: ./../postgresql-server/bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../postgresql-server/schema/
              target: /opt/mediacloud/schema/
            - type: bind
              source: ./../postgresql-server/conf/
              target: /etc/postgresql/12/main/

    rabbitmq-server:
        image: dockermediacloud/rabbitmq-server:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 5672
            - 15672
        volumes:
            - type: bind
              source: ./../rabbitmq-server/conf/
              target: /etc/rabbitmq/
